public class li extends lu<cht> {
   public li(iy $$0) {
      super($$0, iw.j);
   }

   @Override
   protected void b() {
      this.a(akk.a).a(cia.W).a(cia.U).a(cia.S).a(cia.Q);
      this.a(akk.b).a(akk.a).a(cia.V).a(cia.R).a(cia.T).a(cia.P).a(cia.O);
      this.a(akk.c).a(cia.L).a(cia.M);
      this.a(akk.d).a(cia.J).a(cia.K);
      this.a(akk.e).a(cia.D).a(cia.G).a(cia.H).a(cia.I).a(cia.F);
      this.a(akk.f).a(cia.A).a(cia.B).a(cia.C);
      this.a(akk.g).a(cia.t).a(cia.v).a(cia.u);
      this.a(akk.h).a(cia.p).a(cia.q).a(cia.n).a(cia.o);
      this.a(akk.i).a(cia.z).a(cia.x).a(cia.y);
      this.a(akk.j).a(cia.i).a(cia.j).a(cia.k).a(cia.m).a(cia.l).a(cia.E);
      this.a(akk.k).a(cia.r).a(cia.s).a(cia.w);
      lu.a<cht> $$0 = this.a(akk.m);
      cig.a.a.b().forEach($$1x -> $$0.a($$1x));
      lu.a<cht> $$1 = this.a(akk.l);
      cig.a.b.b().forEach($$1x -> $$1.a($$1x));
      this.a(akk.n).a(cia.ag).a(cia.ah).a(cia.ai).a(cia.aj).a(cia.ak);
      this.a(akk.p).a(akk.c);
      this.a(akk.q).a(cia.f);
      this.a(akk.r).a(cia.q).a(cia.d).a(cia.F);
      this.a(akk.s).a(cia.z).a(cia.x);
      this.a(akk.t)
         .a(akk.b)
         .a(akk.d)
         .a(akk.c)
         .a(akk.e)
         .a(akk.g)
         .a(akk.h)
         .a(akk.i)
         .a(akk.j)
         .a(cia.N)
         .a(cia.X)
         .a(cia.e)
         .a(cia.w)
         .a(cia.f)
         .a(cia.r)
         .a(cia.d)
         .a(cia.b)
         .a(cia.c)
         .a(cia.g)
         .a(cia.h)
         .a(cia.s)
         .a(cia.Y)
         .a(cia.Z);
      this.a(akk.u).a(akk.f);
      this.a(akk.W).a(cia.aa);
      this.a(akk.v).a(akk.a);
      this.a(akk.V).a(akk.b).a(akk.d);
      this.a(akk.w).a(cia.V).a(cia.T).a(cia.R).a(cia.W).a(cia.U).a(cia.S);
      this.a(akk.x).a(cia.P).a(cia.O).a(cia.Q);
      this.a(akk.y).a(cia.f).a(cia.b).a(cia.r).a(cia.d).a(cia.p).a(akk.e).a(cia.E);
      this.a(akk.z).a(cia.f);
      this.a(akk.A).a(akk.i);
      this.a(akk.B).a(akk.b);
      this.a(akk.C).a(cia.g).a(cia.h);
      this.a(akk.D).a(akk.f).a(akk.g).a(cia.s).a(cia.w).a(cia.N).a(akk.e);
      this.a(akk.E).a(akk.c).a(akk.d).a(akk.h).a(akk.j).a(cia.X).a(cia.e).a(cia.Y).a(cia.Z).a(cia.r).a(cia.d).a(cia.b).a(cia.c);
      this.a(akk.F).a(akk.c);
      this.a(akk.G).a(akk.b);
      this.a(akk.I).a(cia.g);
      this.a(akk.J).a(cia.f);
      this.a(akk.K).a(cia.b).a(cia.D);
      this.a(akk.L).a(cia.r);
      this.a(akk.M).a(cia.d);
      this.a(akk.N).a(cia.p);
      this.a(akk.O).a(cia.l);
      this.a(akk.o)
         .a(cia.b)
         .a(cia.c)
         .a(cia.d)
         .a(cia.e)
         .a(cia.f)
         .a(cia.i)
         .a(cia.j)
         .a(cia.k)
         .a(cia.l)
         .a(cia.m)
         .a(cia.n)
         .a(cia.o)
         .a(cia.p)
         .a(cia.q)
         .a(cia.r)
         .a(cia.s)
         .a(cia.t)
         .a(cia.u)
         .a(cia.v)
         .a(cia.w)
         .a(cia.x)
         .a(cia.y)
         .a(cia.z)
         .a(cia.A)
         .a(cia.B)
         .a(cia.C)
         .a(cia.D)
         .a(cia.E)
         .a(cia.F)
         .a(cia.G)
         .a(cia.H)
         .a(cia.I)
         .a(cia.X)
         .a(cia.Y)
         .a(cia.Z);
      this.a(akk.H).a(akk.l);
      this.a(akk.P).a(akk.m);
      this.a(akk.Q).a(cia.ae);
      this.a(akk.R).a(cia.ad).a(cia.ab).a(cia.ae).a(cia.ac);
      this.a(akk.S).a(cia.aa);
      this.a(akk.T).a(akk.m);
      this.a(akk.U).a(cia.ah).a(cia.ai);
      this.a(akk.aa).a(cia.O);
      this.a(akk.X).a(akk.b).a(akk.d);
      this.a(akk.Y).a(cia.g).a(cia.h);
      this.a(akk.Z).a(akk.b).a(akk.d).a(cia.g).a(cia.h);
      this.a(akk.ab).a(cia.X);
      this.a(akk.ac).a(cia.X);
      this.a(akk.ad).a(cia.a);
      this.a(akk.ae).a(cia.d).a(cia.e).a(cia.G).a(cia.H).a(cia.F).a(cia.V).a(cia.W).a(cia.E).a(cia.aa).a(cia.K).a(cia.q).a(cia.M).a(akk.n);
      this.a(akk.af).a(cia.f).a(cia.O).a(akk.i).a(akk.k).a(akk.m).a(akk.f).a(cia.h);
      this.a(akk.ag).a(cia.f);
      this.a(akk.ah).a(akk.d);
      this.a(akk.ai).a(cia.Z);
      this.a(akk.aj).a(cia.V).a(cia.W);
      this.a(akk.ak).a(akk.d);
      this.a(akk.al).a(cia.g).a(cia.h);
   }
}
