import java.util.List;

public class nh {
   public static final don a = new dov(akl.aV);
   public static final don b = new dov(akl.aW);
   public static final don c = new dov(akl.aX);
   public static final don d = new dnx(cju.df);
   public static final don e = new dov(akl.aY);
   public static final List<dgf.a> f = List.of(dgf.a(b, cju.J.m()), dgf.a(c, cju.K.m()));
   public static final List<dgf.a> g = List.of(dgf.a(b, cju.H.m()), dgf.a(c, cju.I.m()));
   public static final List<dgf.a> h = List.of(dgf.a(b, cju.ci.m()), dgf.a(c, cju.cj.m()));
   public static final List<dgf.a> i = List.of(dgf.a(b, cju.aE.m()), dgf.a(c, cju.aF.m()));
   public static final List<dgf.a> j = List.of(dgf.a(b, cju.px.m()), dgf.a(c, cju.py.m()));
   public static final List<dgf.a> k = List.of(dgf.a(b, cju.L.m()), dgf.a(c, cju.M.m()));
   public static final hc<ddg<dgf, ?>> l = ne.a("ore_magma", ddt.J, new dgf(d, cju.jv.m(), 33));
   public static final hc<ddg<dgf, ?>> m = ne.a("ore_soul_sand", ddt.J, new dgf(d, cju.dg.m(), 12));
   public static final hc<ddg<dgf, ?>> n = ne.a("ore_nether_gold", ddt.J, new dgf(d, cju.N.m(), 10));
   public static final hc<ddg<dgf, ?>> o = ne.a("ore_quartz", ddt.J, new dgf(d, cju.gc.m(), 14));
   public static final hc<ddg<dgf, ?>> p = ne.a("ore_gravel_nether", ddt.J, new dgf(d, cju.G.m(), 33));
   public static final hc<ddg<dgf, ?>> q = ne.a("ore_blackstone", ddt.J, new dgf(d, cju.oc.m(), 33));
   public static final hc<ddg<dgf, ?>> r = ne.a("ore_dirt", ddt.J, new dgf(a, cju.j.m(), 33));
   public static final hc<ddg<dgf, ?>> s = ne.a("ore_gravel", ddt.J, new dgf(a, cju.G.m(), 33));
   public static final hc<ddg<dgf, ?>> t = ne.a("ore_granite", ddt.J, new dgf(a, cju.c.m(), 64));
   public static final hc<ddg<dgf, ?>> u = ne.a("ore_diorite", ddt.J, new dgf(a, cju.e.m(), 64));
   public static final hc<ddg<dgf, ?>> v = ne.a("ore_andesite", ddt.J, new dgf(a, cju.g.m(), 64));
   public static final hc<ddg<dgf, ?>> w = ne.a("ore_tuff", ddt.J, new dgf(a, cju.pk.m(), 64));
   public static final hc<ddg<dgf, ?>> x = ne.a("ore_coal", ddt.J, new dgf(k, 17));
   public static final hc<ddg<dgf, ?>> y = ne.a("ore_coal_buried", ddt.J, new dgf(k, 17, 0.5F));
   public static final hc<ddg<dgf, ?>> z = ne.a("ore_iron", ddt.J, new dgf(f, 9));
   public static final hc<ddg<dgf, ?>> A = ne.a("ore_iron_small", ddt.J, new dgf(f, 4));
   public static final hc<ddg<dgf, ?>> B = ne.a("ore_gold", ddt.J, new dgf(g, 9));
   public static final hc<ddg<dgf, ?>> C = ne.a("ore_gold_buried", ddt.J, new dgf(g, 9, 0.5F));
   public static final hc<ddg<dgf, ?>> D = ne.a("ore_redstone", ddt.J, new dgf(List.of(dgf.a(b, cju.cR.m()), dgf.a(c, cju.cS.m())), 8));
   public static final hc<ddg<dgf, ?>> E = ne.a("ore_diamond_small", ddt.J, new dgf(h, 4, 0.5F));
   public static final hc<ddg<dgf, ?>> F = ne.a("ore_diamond_large", ddt.J, new dgf(h, 12, 0.7F));
   public static final hc<ddg<dgf, ?>> G = ne.a("ore_diamond_buried", ddt.J, new dgf(h, 8, 1.0F));
   public static final hc<ddg<dgf, ?>> H = ne.a("ore_lapis", ddt.J, new dgf(i, 7));
   public static final hc<ddg<dgf, ?>> I = ne.a("ore_lapis_buried", ddt.J, new dgf(i, 7, 1.0F));
   public static final hc<ddg<dgf, ?>> J = ne.a("ore_infested", ddt.J, new dgf(List.of(dgf.a(b, cju.dV.m()), dgf.a(c, cju.qL.m())), 9));
   public static final hc<ddg<dgf, ?>> K = ne.a("ore_emerald", ddt.J, new dgf(List.of(dgf.a(b, cju.eL.m()), dgf.a(c, cju.eM.m())), 3));
   public static final hc<ddg<dgf, ?>> L = ne.a("ore_ancient_debris_large", ddt.af, new dgf(e, cju.nU.m(), 3, 1.0F));
   public static final hc<ddg<dgf, ?>> M = ne.a("ore_ancient_debris_small", ddt.af, new dgf(e, cju.nU.m(), 2, 1.0F));
   public static final hc<ddg<dgf, ?>> N = ne.a("ore_copper_small", ddt.J, new dgf(j, 10));
   public static final hc<ddg<dgf, ?>> O = ne.a("ore_copper_large", ddt.J, new dgf(j, 20));
   public static final hc<ddg<dgf, ?>> P = ne.a("ore_clay", ddt.J, new dgf(a, cju.da.m(), 33));
}
